/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_security_util_VoiceLinkJNI */

#ifndef _Included_com_example_security_util_VoiceLinkJNI
#define _Included_com_example_security_util_VoiceLinkJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_security_util_VoiceLinkJNI
 * Method:    AnomalyDetectionJNI
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_security_util_VoiceLinkJNI_AnomalyDetectionJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
