/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_security_util_VoiceLinkC */

#ifndef _Included_com_example_security_util_VoiceLinkC
#define _Included_com_example_security_util_VoiceLinkC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_security_util_VoiceLinkC
 * Method:    startVoiceJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_security_util_VoiceLinkC_startVoiceJNI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_security_util_VoiceLinkC
 * Method:    closeVoiceJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_security_util_VoiceLinkC_closeVoiceJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
